### ISSUE TITLE
Usage with Webpack

### ISSUE THREAD

**Issue by Austio** [nettofarah/axios-vcr#1]
Hello,

So this is really an interoperability question.  Axios-VCR works and works well.  Would be a good addition to community if was able to get a setup for it with webpack.  

When I add axios-vcr to a project where I am using webpack I get an error related to `fs` not being defined.  That is related to the fs being stubbed out by webpack.  

I tried with `target: "node"`, which runs your project as if it were in a node-server setup but then get something related to `process` not being found, when i define the process i end up going down a rabbit hole of other issues.

Do you have any recommendations for a setup for this to allow axios-vcr access to fs for read/write but keep everything else in the project working as is?

Thanks so much for axios-vcr and any help!

**Comment by nettofarah** [comment]
Hi, @Austio!

That's a good question.
I'll need a little more info before I can help you more effectively, though.

How are you running your tests today?
I ask this because I'm running my tests today using mocha directly through node.

I had never considered running axios-vcr in the browser context. But I'm sure we can work something out.

**Comment by Austio** [comment]
Ah good thought, I'm using karma and jasmine with phantomJS.

**Comment by nettofarah** [comment]
So I'm assuming you should have node installed. I'm surprised `fs` is not around in your case.
Is there any special reason to use webpack in your tests?

I usually run all my tests from node itself.

**Comment by Austio** [comment]
Great question, 

We have a frontend framework that we are building around (vue.js) so we need babel and vue-loader to get things to js.  

fs does exist when i set `target: node` in my webpack config but then i have other issue with the project.  I am trying to think of a way to allow axios-vcr to have the access it needs, i'm gandering at externals right now.

**Comment by nettofarah** [comment]
Here's an idea.
You could try to fork this repo and add `fs` as a dependency to `package.json`
Maybe that will do something?

**Comment by nettofarah** [comment]
Can you create a simple app or gist on github and post it here?
I can try to reproduce the issue on my machine and see if there's anything I can do to fix things in the library maybe.

**Comment by Austio** [comment]
https://github.com/Austio/axios-vcr

Tried to pull out the most relevant pieces.  To reproduce.

yarn install
yarn run unit

**Comment by nettofarah** [comment]
Hey, @Austio.
I managed to reproduce the bug with your sample app, and here's what I learned.

- Webpack doesn't ship with a `fs` replacement by default
- Switching your webpack config to use`target: node` will work fine, since webpack will assume it should use node's version of `fs`
- PhantomJS has its own `fs` module (which I'm not sure is 100% compatible with node's fs package)
- PhantomJS doesn't ship with support the `process` global variable. So even if you use webpack with `target: 'node'` you won't end up going too far because of this problem.
- I'm not sure if Karma/PhantomJS would even allow you to write to the disk within your unit tests, which would in turn render `axios-vcr`s use-case useless.

Here are my suggestions going forward (and my preferred way to test client side js):

- Use a full node solution for your unit tests. There are some really great libraries like `jsdom` that implement a fully mocked version of the DOM in node. With that you can leverage everything from the node ecosystem.

- Drop the dependency on Webpack. You don't really need to compile your code if you're using node. You can just include your modules and write some truly unit tests.

- Reconsider the use of PhantomJS for unit tests (and even karma). While I think PhantomJS is a great tool, it may be overkill to load an entire browser suite to execute javascript (again, you can do this in node)

Here's one example of `jsdom` in a react codebase: https://github.com/nettofarah/react-flexible-switch/blob/master/test/helpers/fakeDom.js

Good luck with your project. And let me know if there's anything else I can do to help.

**Comment by Austio** [comment]
@nettofarah  Thanks so much for gandering, good luck to you as well.  I'll post something here if i end up with a solid solution.
